version: "3"
services:
  python:
    restart: always
    build: .
    container_name: 'gans-in-actions-jupyter'
    working_dir: '/root/'
    tty: true 
    volumes:
      - ../:/root/
    ports:
      - "8080:8080"
    command: jupyter-lab --ip 0.0.0.0 --port=8080 --allow-root --no-browser
